### ISSUE TITLE
Help to install

### ISSUE THREAD

**Issue by jordanorc** [LukasBombach/sblendid#1]
Hello, I would like install and test this library, but seems it is not published on npm yet. There is any way to test it? I'm having a lot of problems with noble because of this https://github.com/abandonware/noble/issues/15 and I want to test sblendid library to see if it can fit my needs.

**Comment by LukasBombach** [comment]
Hey @jordanorc I am heavily working on this. Right now, you won't be to happy with this because i keep pushing stuff to the master as I work on this and break and unbreak this.

I am currently writing unit tests for the library and will release soon. I you bear with me a little (maybe 2 weeks) it should be published and I can ping you here.

**Comment by jordanorc** [comment]
Hi Lukas, thank you very much for the reply and your work on this library. I'm having a lot of issues on Ubuntu using Noble and would be great to have an alternative for it. Please let me know when you finish it.

**Comment by LukasBombach** [comment]
Will do

**Comment by LukasBombach** [comment]
Hey @jordanorc just letting you know this project isn't dead, I am currently writing unit tests like crazy as I am aiming for 100% test coverage

**Comment by jordanorc** [comment]
Hi @LukasBombach, I'm following your commits :) Thank you very much for your work and let me know If I can help someway. I'm anxious to test it, because I'm working on a project ẃhere bluetooth devices communication is crucial. Let me know when it is minimal ready to test :)

**Comment by mafaneh** [comment]
I’m very interested too!

**Comment by LukasBombach** [comment]
Hey @jordanorc @mafaneh , I have silently published version `0.2.0` to npm. You can try to do

```bash
npm install @sblendid/sblendid @sblendid/adapter-node
```

Currently this is `Windows` and `macOS` only as this is not the final version yet, but it is a preview that you can try out if you want to. If you find any bugs _please_ tell me (open an issue), that would be awesome!

I am not closing this issue as I still need to work my way to `v1.0.0` with `Linux` support and fix bugs that might be there.

**Comment by jordanorc** [comment]
Hey @LukasBombach, thanks for the reply. I will try it asap. I'm working on Linux right now, but I'll install a windows VM to test it.

**Comment by LukasBombach** [comment]
Working on it: https://github.com/LukasBombach/sblendid/pull/5

**Comment by LukasBombach** [comment]
I decided to close this issue since sblendid can already be installed. It is still lacking Linux support but this already addressed in other issues.
